### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by Stearinrin**

### CODE REVIEW

**Comment by otariidae** [comment]
Why do you modify `db/schema.rb` and `yarn.lock`?
These files have nothing to do with favicon.

**Comment by Stearinrin** [comment]
db/schema.rb and yarn.lock was automatically modified when running in my local environment.

**Comment by otariidae** [comment]
Remove them from the commit.
If you still want to merge them, open a new pull request.

**Comment by otariidae** [comment]
Thanks for your first contribution.

**Comment by Stearinrin** [comment]
Thank You for helping me!

**Pull request merged**
